In [1]:
import os


In [2]:
os.chdir("D:\lab session\day1")

In [3]:
os.getcwd()

'D:\\lab session\\day1'

In [4]:
import numpy as np
import sympy as sp

In [6]:
A = [[0,2],[6,4]]
A_array = np.array(A)

In [7]:
A_array

array([[0, 2],
       [6, 4]])

In [8]:
A_mat = np.matrix(A_array)
sp.Matrix(A_mat)

Matrix([
[0, 2],
[6, 4]])

In [9]:
A_T = np.transpose(A_mat)
A_T

matrix([[0, 6],
        [2, 4]])

In [10]:
sp.Matrix(A_T)

Matrix([
[0, 6],
[2, 4]])

In [11]:
A_mat*5

matrix([[ 0, 10],
        [30, 20]])

In [12]:
sp.Matrix(A_mat*5)

Matrix([
[ 0, 10],
[30, 20]])

In [15]:
B = [[9,7],[7,8]]
B_mat = np.matrix(np.array(B))

In [16]:
sp.Matrix(B_mat)

Matrix([
[9, 7],
[7, 8]])

In [17]:
sp.Matrix(A_mat)

Matrix([
[0, 2],
[6, 4]])

In [18]:
A_mat + B_mat

matrix([[ 9,  9],
        [13, 12]])

In [20]:
sp.Matrix(A_mat + B_mat)

Matrix([
[ 9,  9],
[13, 12]])

In [25]:
np.linalg.matrix_rank(A_mat + B_mat)

2

In [24]:
np.linalg.det(A_mat)

-12.0

In [28]:
A_inv=np.linalg.inv(A_mat)

In [29]:
sp.Matrix(A_inv)

Matrix([
[-0.333333333333333, 0.166666666666667],
[               0.5,                 0]])

In [31]:
A_id=np.dot(A_mat,A_inv)

In [32]:
sp.Matrix(A_id)

Matrix([
[1.0,   0],
[  0, 1.0]])

In [33]:
A_sym = (A_mat + np.transpose(A_mat))/2

In [34]:
sp.Matrix(A_sym)

Matrix([
[  0, 4.0],
[4.0, 4.0]])

In [35]:
np.linalg.matrix_rank(A_sym)

2

In [36]:
a_eig, a_evec = np.linalg.eig(A_sym)

In [37]:
a_eig

array([-2.47213595,  6.47213595])

In [38]:
a_evec

matrix([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]])

In [39]:
print(np.linalg.eig(A_sym))

(array([-2.47213595,  6.47213595]), matrix([[-0.85065081, -0.52573111],
        [ 0.52573111, -0.85065081]]))


In [40]:
A_new=np.dot(A_mat,np.transpose(A_mat))

In [41]:
sp.Matrix(A_new)

Matrix([
[4,  8],
[8, 52]])

In [42]:
a_eig, a_evec = np.linalg.eig(A_new)

In [43]:
a_eig

array([ 2.70177872, 53.29822128])

In [44]:
a_evec

matrix([[-0.98708746, -0.16018224],
        [ 0.16018224, -0.98708746]])

In [45]:
Lambda = np.diag(a_eig)

In [46]:
sp.Matrix(Lambda)

Matrix([
[2.70177871865297,               0],
[               0, 53.298221281347]])

In [47]:
P = a_evec

In [48]:
sp.Matrix(P)

Matrix([
[-0.987087457637497, -0.160182243006967],
[ 0.160182243006967, -0.987087457637497]])

In [50]:
sp.Matrix(np.dot(P,np.transpose(P)))

Matrix([
[                 1.0, 5.42012381150499e-18],
[5.42012381150499e-18,                  1.0]])

In [53]:
np.sqrt(Lambda)

array([[1.64370883, 0.        ],
       [0.        , 7.30056308]])

In [59]:
alpha = -0.5 
a_eig**alpha

array([0.60838026, 0.13697574])

In [60]:
A_new_aplha=np.dot(np.dot(P,np.diag(a_eig**alpha)),np.transpose(P))

In [61]:
sp.Matrix(A_new_aplha)

Matrix([
[ 0.596284793999944, -0.074535599249993],
[-0.074535599249993,  0.149071198499986]])