# Dr. Radhendushka Srivastava and Dr. Jovi D'Silva

# Linear algebra

In [43]:
import numpy as np
import sympy as sp
from sklearn.utils.extmath import randomized_svd

## Creating a matrix entry wise

In [2]:
#List

A = [[1,7,9],[8,6,5],[2,4,3]] 
B = [[3,8,5],[7,9,4],[2,1,6]]
print(A)
print(B)


[[1, 7, 9], [8, 6, 5], [2, 4, 3]]
[[3, 8, 5], [7, 9, 4], [2, 1, 6]]


In [3]:
A1 = np.array(A) #creating array using array func from numpy
B1 = np.array(B)
print('Matrix A1:'+'\n', np.matrix(A1))
print('Matrix B1:'+'\n', np.matrix(B1))


Matrix A1:
 [[1 7 9]
 [8 6 5]
 [2 4 3]]
Matrix B1:
 [[3 8 5]
 [7 9 4]
 [2 1 6]]


In [4]:
print('Matrix A1:')
sp.Matrix(A1)


Matrix A1:


Matrix([
[1, 7, 9],
[8, 6, 5],
[2, 4, 3]])

In [5]:
print('Matrix B1 :')
sp.Matrix(A1)

Matrix B1 :


Matrix([
[1, 7, 9],
[8, 6, 5],
[2, 4, 3]])

In [6]:
print('Array A:')
np.array(A)

Array A:


array([[1, 7, 9],
       [8, 6, 5],
       [2, 4, 3]])

In [7]:
print('Array B:')
np.array(B)

Array B:


array([[3, 8, 5],
       [7, 9, 4],
       [2, 1, 6]])

In [8]:
print(A1[2,2]) #print first row and first column of matrix (index row range 0 to number of row-1, index col range 0 to number of col-1)

3


## Creating a column vector

## Inputing matrics of given dimension (rows and columns)

In [9]:
my_array = [[10,1,2],[1,6,2],[2,6,7]]
M = np.transpose(my_array) #to create a columnwise array we use transpose func from numpy library
print("Matrix with column wise creation \n",M)

Matrix with column wise creation 
 [[10  1  2]
 [ 1  6  6]
 [ 2  2  7]]


## Extracting certain row(s) or column(s) of a matrix

In [10]:
print('First Row of array:', M[0,:]) 
print('First Column of array:',M[:,0])

First Row of array: [10  1  2]
First Column of array: [10  1  2]


## Deleting a specific row(s) or column(s) of a matrix

In [11]:
#delete 2nd row
R_del = np.delete(M,1,axis=0) #axis=0 means rowwise
print("Original:\n",M)
print("\n2nd row Deleted:\n",R_del)

Original:
 [[10  1  2]
 [ 1  6  6]
 [ 2  2  7]]

2nd row Deleted:
 [[10  1  2]
 [ 2  2  7]]


In [12]:
#delete 2nd column
C_del = np.delete(M,1,axis=1) #axi=1 means col wise
print("Original:\n",M)
print("\n2nd column Deleted:\n",C_del)

Original:
 [[10  1  2]
 [ 1  6  6]
 [ 2  2  7]]

2nd column Deleted:
 [[10  2]
 [ 1  6]
 [ 2  7]]


## Transpose and rank of the matrix

In [13]:
MT = M.T #calculating transpose of matrix M
print(MT)

[[10  1  2]
 [ 1  6  2]
 [ 2  6  7]]


In [14]:
MR = np.linalg.matrix_rank(M) #calculating rank of matrix M using matrix_rank from linear algebra library in numpy package
print(MR)

3


## Determinant of a square matrix

In [15]:
MD = np.linalg.det(M) #calculating determinant of matrix mat using det from linear algebra library in numpy package
print(MD)

285.00000000000006


In [16]:
sp.Matrix(M).det() #calculating determinant of matrix mat using sumpy package

285

## Inverse of a square matrix

In [17]:
MI = np.linalg.inv(M) #calculating inverse of matrix M using inv from linear algebra library in numpy package
print("Inverse of Matrix: \n",MI)
#Print nicely like the inverse of the matrix M is = with proper allignment 

Inverse of Matrix: 
 [[ 0.10526316 -0.01052632 -0.02105263]
 [ 0.01754386  0.23157895 -0.20350877]
 [-0.03508772 -0.06315789  0.20701754]]



## Addition and substraction of two matrices

In [18]:
print('Matrix M:'+'\n', M)

Matrix M:
 [[10  1  2]
 [ 1  6  6]
 [ 2  2  7]]


In [19]:
print('Matrix M :')
sp.Matrix(M)

Matrix M :


Matrix([
[10, 1, 2],
[ 1, 6, 6],
[ 2, 2, 7]])

In [20]:
# create a second integer matrix N (3x3) of all ones using numpy
N = np.ones((3, 3),dtype=np.int8)

In [21]:
print('Matrix N:'+'\n', N)

Matrix N:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [22]:
print('Matrix N :')
sp.Matrix(N)

Matrix N :


Matrix([
[1, 1, 1],
[1, 1, 1],
[1, 1, 1]])

In [23]:
MA = M + N #addition of matrices
MS = M - N #substraction of matrices
print("Addition of Matrices: \n",MA)
print("Substraction of Matrices: \n",MS)

Addition of Matrices: 
 [[11  2  3]
 [ 2  7  7]
 [ 3  3  8]]
Substraction of Matrices: 
 [[9 0 1]
 [0 5 5]
 [1 1 6]]


In [24]:
sp.Matrix(M)+sp.Matrix(N)

Matrix([
[11, 2, 3],
[ 2, 7, 7],
[ 3, 3, 8]])

In [25]:
sp.Matrix(M)-sp.Matrix(N)

Matrix([
[9, 0, 1],
[0, 5, 5],
[1, 1, 6]])

## Element wise product of two matricies

In [26]:
MEle = np.multiply(M,N) #calculating element wise product using multiply from numpy
print('Element Wise product'+'\n',MEle)

Element Wise product
 [[10  1  2]
 [ 1  6  6]
 [ 2  2  7]]


In [27]:
from sympy import matrix_multiply_elementwise
matrix_multiply_elementwise(sp.Matrix(M), sp.Matrix(N))

Matrix([
[10, 1, 2],
[ 1, 6, 6],
[ 2, 2, 7]])

## Matrix multiplication

In [28]:
MMul = np.dot(M,N) #calculating matrix product usig dot from numpy
print('Matrix Multiplication'+'\n',MMul)

Matrix Multiplication
 [[13 13 13]
 [13 13 13]
 [11 11 11]]


In [29]:
sp.Matrix(M)*sp.Matrix(N)

Matrix([
[13, 13, 13],
[13, 13, 13],
[11, 11, 11]])

## Eigen values and eigen vectors of a square matrix

In [47]:
print(M)
MEig , MEigV = np.linalg.eig(M) #calculating eigen values and eigen vectors
print('Eigen values'+'\n',MEig)
print('Eigen Vectors'+'\n',MEigV)
P=MEigV
print(P)
print(P.T)
A=np.dot(P,P.T)
print(A)
#Print nicely, so that one could see what are eigen value vector and eigen vector matrix.
#Rows of eigen vector matrix corresponds to eigen values of the matrix.

[[10  1  2]
 [ 1  6  6]
 [ 2  2  7]]
Eigen values
 [12.23606798  7.76393202  3.        ]
Eigen Vectors
 [[ 6.76113763e-01  6.08017945e-01  2.36746848e-16]
 [ 5.64268559e-01 -7.28534834e-01 -8.94427191e-01]
 [ 4.73783888e-01 -3.15517311e-01  4.47213595e-01]]
[[ 6.76113763e-01  6.08017945e-01  2.36746848e-16]
 [ 5.64268559e-01 -7.28534834e-01 -8.94427191e-01]
 [ 4.73783888e-01 -3.15517311e-01  4.47213595e-01]]
[[ 6.76113763e-01  5.64268559e-01  4.73783888e-01]
 [ 6.08017945e-01 -7.28534834e-01 -3.15517311e-01]
 [ 2.36746848e-16 -8.94427191e-01  4.47213595e-01]]
[[ 0.82681564 -0.06145251  0.12849162]
 [-0.06145251  1.64916201  0.0972067 ]
 [ 0.12849162  0.0972067   0.52402235]]


In [31]:
sp.Matrix(MEig)

Matrix([
[12.2360679774998],
[7.76393202250021],
[             3.0]])

In [32]:
sp.Matrix(MEigV)

Matrix([
[ 0.67611376320047,  0.608017945186653, 2.36746848099096e-16],
[0.564268558981482, -0.728534834114434,   -0.894427190999916],
[0.473783888028984,  -0.31551731143133,    0.447213595499958]])

## Spectral value decomposition of a square symmetric matrix

In [46]:
#use singular value decomposition 
#from scipy.linalg import svd
U , Si, V_T = randomized_svd(M,n_components=3)
#left singular vectors
print("Left Singular Vectors: \n", U)
#Singular Values
print("Singular Values: \n",Si)
#Right Singular Vectors
print("Right Singular Vectors: \n", V_T)


#Then spectral value decomposition 
#connect it with eigen value and eigen vector
#https://www.section.io/engineering-education/singular-value-decomposition-in-python/
#above link may be useful

Left Singular Vectors: 
 [[ 0.64120837  0.75946333 -0.10985116]
 [ 0.5543148  -0.55740558 -0.61808908]
 [ 0.53064764 -0.33543177  0.77839489]]
Singular Values: 
 [12.60945079  8.27945601  2.72990093]
Right Singular Vectors: 
 [[ 0.63664104  0.39877966  0.66004771]
 [ 0.76893507 -0.39324247 -0.50408254]
 [-0.05854092 -0.82845347  0.55698996]]


C:\Users\rsriv\anaconda3\lib\site-packages\sklearn\utils\extmath.py:368: FutureWarning: If 'random_state' is not supplied, the current default is to use 0 as a fixed seed. This will change to  None in version 1.2 leading to non-deterministic results that better reflect nature of the randomized_svd solver. If you want to silence this warning, set 'random_state' to an integer seed or to None explicitly depending if you want your code to be deterministic or not.
  warnings.warn(


In [34]:
sp.Matrix(U)

Matrix([
[-0.641208374854325,  0.759463325122299, -0.109851162082416],
[-0.554314802135541,  -0.55740558313133, -0.618089084216391],
[-0.530647642178981, -0.335431772031516,  0.778394890888735]])

In [35]:
sp.Matrix(Si)

Matrix([
[12.6094507867485],
[8.27945600754632],
[2.72990092781296]])

In [36]:
sp.Matrix(V_T)

Matrix([
[ -0.636641037805804, -0.398779657977648, -0.660047705370436],
[  0.768935074747181, -0.393242468437682, -0.504082544669606],
[-0.0585409241906504, -0.828453466043971,   0.55698995933018]])

# Some special matrices 

## Matrix of dimension 3 by 3 with each element as 1

In [37]:
S = np.ones((3,3))
print("Special Ones Matrix: \n",S)

Special Ones Matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
sp.Matrix(S)

Matrix([
[1.0, 1.0, 1.0],
[1.0, 1.0, 1.0],
[1.0, 1.0, 1.0]])

## Creating a diagonal matrix from a given vector of dimension 5

In [39]:
v = [7,9,5,4,3]
vm = np.diag(v)
print("Diagonal Matrix \n",vm)

Diagonal Matrix 
 [[7 0 0 0 0]
 [0 9 0 0 0]
 [0 0 5 0 0]
 [0 0 0 4 0]
 [0 0 0 0 3]]


In [40]:
sp.Matrix(vm)

Matrix([
[7, 0, 0, 0, 0],
[0, 9, 0, 0, 0],
[0, 0, 5, 0, 0],
[0, 0, 0, 4, 0],
[0, 0, 0, 0, 3]])

## Given 3 vectors of dimension 5, combine them into a matrix of dimension 3 by 5

In [41]:
v = [7,9,5,4,3]
v1 = [8,4,2,6,1]
v2 = [15,18,20,25,11]
vmat = np.array([v,v1,v2])
print("Matrix after vectors joined: \n",vmat)

Matrix after vectors joined: 
 [[ 7  9  5  4  3]
 [ 8  4  2  6  1]
 [15 18 20 25 11]]


In [42]:
sp.Matrix(vmat)

Matrix([
[ 7,  9,  5,  4,  3],
[ 8,  4,  2,  6,  1],
[15, 18, 20, 25, 11]])